import type { Metadata } from "next";
import "./globals.css";
import Script from "next/script";

export const metadata: Metadata = {
    title: "College Khabar",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en" className="">
            <body
                className="bg-white min-w-screen min-h-screen box-border"
                suppressHydrationWarning={true}
            >
                {children}
            </body>
        </html>
    );
}
