import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
    title: "CollegeKhabar",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className="bg-white min-w-screen min-h-screen" suppressHydrationWarning={true}>
                {children}
            </body>
        </html>
    );
}
